before_script:
  - sudo yum install -y bzip2
deploy:
  script:
    - mvn clean install
    - sudo cp ~/.m2/repository/cf/nirvandil/backend/1.0-SNAPSHOT/backend-1.0-SNAPSHOT.jar /var/www/app/fhdomainadder.jar
    - sudo sync
    - sudo chmod +x /var/www/app/fhdomainadder.jar
    - sudo systemctl restart fhdomainadder
  only:
    - master